### ISSUE TITLE
ClassCaseException when saving a model

### ISSUE THREAD

**Issue by expert-fb** [chungkwong/text-classifier-collection#3]
I run into a ClassCastException when trying to save an underlying  FrequencyModel from a base SvmClassifierFactory

`Exception in thread "main" java.lang.ClassCastException: com.github.chungkwong.classifier.DocumentVectorsModel cannot be cast to com.github.chungkwong.classifier.FrequenciesModel
	at com.github.chungkwong.classifier.example.Demo2.save(Demo2.java:50)
	at com.github.chungkwong.classifier.example.Demo2.main(Demo2.java:42)
`

I'm a bit lost concerning the typing. My attached code doesn't give me any compilation errors. Is there any re-typing in the background?
What is the preferred way to save a model in order to re-use it later?

Thanks for any hint!

code an test data are attached

[Demo2.zip](https://github.com/chungkwong/text-classifier-collection/files/3324555/Demo2.zip)

**Comment by chungkwong** [comment]
Because of limitations in type inference of Java's generic, Java's compiler failed to figure out the correct type of the model. In fact, DocumentVectorsModel is used instead of FrequenciesModel for SVM. The following code should run with the latest commit, but saving the trained classifier may be better.

```java
public class Demo2{
	private static final String DATA_FILE="data/foobar.csv";
	public static void main(String[] args){
		//Create a naive Bayesian ClassifierFactory. For other classifier, use
		//new SvmClassifierFactory(),new KNearestClassifierFactory().setK(k)
		//new C45ClassifierFactory() or new TfIdfClassifierFactory()
		SvmClassifierFactory baseClassifierFactory=new SvmClassifierFactory<>();
		//Select features using Tf-Idf
		baseClassifierFactory.setFeatureSelector(new TfIdfFeatureSelector<>(5000));
		//Create a tokenizer
		Function<String,Stream<String>> tokenizer=TextPreprocessors.getJavaTokenizer(BreakIterator.getWordInstance(Locale.GERMAN)); //getCharacterInstance(Locale.GERMAN)
		// Create token stream filter
		Function<Stream<String>,Stream<String>> postTokenize
				=TextPreprocessors.getWhitespaceFilter()
						.compose(TextPreprocessors.getDowncaser())
						.andThen(TextPreprocessors.getNgramGenerator(1,2));
		//Create a text ClassifierFactory with given preprocessors applied
//		PreprocessClassifierFactory<FrequenciesModel<String>,String,Frequencies<String>> classifierFactory=new PreprocessClassifierFactory<>(
//				TextPreprocessors.of(tokenizer,postTokenize),baseClassifierFactory);
		// Create a text ClassifierFactory with given preprocessors applied
		PreprocessClassifierFactory<DocumentVectorsModel<String>,String,Frequencies<String>> classifierFactory
				=new PreprocessClassifierFactory<>(
						TextPreprocessors.of(tokenizer,postTokenize),baseClassifierFactory);
		PreprocessModel<DocumentVectorsModel<String>,String,Frequencies<String>> model=classifierFactory.createModel();
		model.train(TextDatasetHelper.csvRecords(new File(DATA_FILE).toPath(),1,0));
		Classifier<String> classifier=classifierFactory.getClassifier(model);
		save(model);
		//Output the candidates and their scores
//		System.out.println(classifier.getCandidates("To be classified"));
	}
	private static void save(PreprocessModel<DocumentVectorsModel<String>,String,Frequencies<String>> model){
		DocumentVectorsModel<String> fm=model.getUnderlying();
		File modeldir=new File("output/modeldir");
		if(!modeldir.exists()){
			modeldir.mkdirs();
		}
		fm.save(modeldir,Function.identity());
	}
}
```

**Comment by expert-fb** [comment]
Yes, I would prefer to save and reload a trained classifier but I didn't figure out how to do it.
Where do I have to look?
